FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    sysbench \
    postgresql-client \
    openjdk-17-jre \
    wget \
    unzip \
    python3 \
    python3-pip  \
    curl
# Install JMeter
RUN wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz && \
    tar -xzf apache-jmeter-5.6.3.tgz && \
    mv apache-jmeter-5.6.3 /opt/jmeter
ENV PATH="$PATH:/opt/jmeter/bin"
WORKDIR /scripts
CMD ["tail", "-f", "/dev/null"]
